import { format } from "date-fns";

type ToastFunction = (options: {
  title: string;
  description: string;
  variant?: "default" | "destructive";
}) => void;

export function exportToCSV(
  sales: any[],
  reportRef: { current: HTMLDivElement | null },
  toast: ToastFunction
) {
  const headers = [
    "Date",
    "Transaction ID",
    "Customer",
    "Items",
    "Payment Method",
    "Amount",
  ];
  const csvRows = [headers];

  sales.forEach((sale) => {
    const row = [
      format(new Date(sale.date), "yyyy-MM-dd HH:mm:ss"),
      sale.id,
      sale.customerName || "Walk-in Customer",
      sale.items.length.toString(),
      sale.paymentMethod === "credit"
        ? "Credit Card"
        : sale.paymentMethod === "cash"
        ? "Cash"
        : "Mobile Payment",
      sale.total.toFixed(2),
    ];
    csvRows.push(row);
  });

  const csvContent = csvRows.map((row) => row.join(",")).join("\n");
  const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.setAttribute("href", url);
  link.setAttribute(
    "download",
    `sales_report_${format(new Date(), "yyyy-MM-dd")}.csv`
  );
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);

  toast({
    title: "Report Exported",
    description: "The sales report has been exported as CSV.",
  });
}

export function printReport(
  reportRef: { current: HTMLDivElement | null },
  sales: any[],
  toast: ToastFunction
) {
  if (!reportRef.current) return;

  const printContent = reportRef.current.innerHTML;
  const printWindow = window.open("", "_blank");
  if (!printWindow) {
    toast({
      title: "Print Error",
      description:
        "Could not open print window. Please check your browser settings.",
      variant: "destructive",
    });
    return;
  }

  printWindow.document.write(`
    <html>
      <head>
        <title>Sales Report - ${format(new Date(), "yyyy-MM-dd")}</title>
        <style>
          body {
            font-family: Arial, sans-serif;
            padding: 20px;
            max-width: 1000px;
            margin: 0 auto;
          }
          h1, h2 {
            text-align: center;
          }
          table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
          }
          th, td {
            padding: 8px;
            text-align: left;
            border-bottom: 1px solid #ddd;
          }
          th {
            background-color: #f2f2f2;
          }
          .report-header {
            display: flex;
            justify-content: space-between;
            margin-bottom: 20px;
          }
          .report-summary {
            margin-bottom: 20px;
          }
        </style>
      </head>
      <body>
        <h1>Sales Report</h1>
        <div class="report-header">
          <div>
            <p><strong>Date:</strong> ${format(new Date(), "MMMM dd, yyyy")}</p>
            <p><strong>Generated by:</strong> POS System</p>
          </div>
          <div>
            <p><strong>Total Sales:</strong> ${sales.length}</p>
            <p><strong>Total Revenue:</strong> $${sales
              .reduce((sum, sale) => sum + sale.total, 0)
              .toFixed(2)}</p>
          </div>
        </div>
        ${printContent}
      </body>
    </html>
  `);

  printWindow.document.close();
  printWindow.focus();
  printWindow.print();
  printWindow.close();

  toast({
    title: "Report Printed",
    description: "The sales report has been sent to the printer.",
  });
}

export function printInvoice(
  sale: any,
  toast: ReturnType<typeof useToast>["toast"]
) {
  const printWindow = window.open("", "_blank");
  if (!printWindow) {
    toast({
      title: "Print Error",
      description:
        "Could not open print window. Please check your browser settings.",
      variant: "destructive",
    });
    return;
  }

  printWindow.document.write(`
    <html>
      <head>
        <title>Invoice - ${sale.id}</title>
        <style>
          body {
            font-family: Arial, sans-serif;
            padding: 20px;
            max-width: 600px;
            margin: 0 auto;
          }
          h1, h2 {
            text-align: center;
          }
          table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
          }
          th, td {
            padding: 8px;
            text-align: left;
            border-bottom: 1px solid #ddd;
          }
          th {
            background-color: #f2f2f2;
          }
        </style>
      </head>
      <body>
        <h1>Invoice</h1>
        <p><strong>Transaction ID:</strong> ${sale.id}</p>
        <p><strong>Date:</strong> ${format(
          new Date(sale.date),
          "MMM dd, yyyy HH:mm"
        )}</p>
        <p><strong>Customer:</strong> ${
          sale.customerName || "Walk-in Customer"
        }</p>
        <h2>Items</h2>
        <table>
          <thead>
            <tr>
              <th>Item</th>
              <th>Quantity</th>
              <th>Price</th>
            </tr>
          </thead>
          <tbody>
            ${sale.items
              .map(
                (item: any) => `
              <tr>
                <td>${item.name}</td>
                <td>${item.quantity}</td>
                <td>$${item.price.toFixed(2)}</td>
              </tr>
            `
              )
              .join("")}
          </tbody>
        </table>
        <p><strong>Total:</strong> $${sale.total.toFixed(2)}</p>
      </body>
    </html>
  `);

  printWindow.document.close();
  printWindow.focus();
  printWindow.print();
  printWindow.close();

  toast({
    title: "Invoice Printed",
    description: `Invoice for transaction ${sale.id} has been sent to the printer.`,
  });
}
